# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zkcluster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[(b'p', 'present'), (b'a', 'absense'), (b'l', 'late')], max_length=1, verbose_name='status')),
            ],
            options={
                'db_table': 'driji_attendance_summary',
            },
        ),
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('phone_number', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='phone number')),
            ],
            options={
                'db_table': 'driji_phonebook',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.SmallIntegerField(choices=[(0, 'User'), (14, 'Administrator')], default=0, verbose_name='privilege')),
                ('password', models.CharField(blank=True, max_length=8, null=True, verbose_name='password')),
                ('group_id', models.CharField(blank=True, max_length=7, null=True, verbose_name='group id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('fullname', models.CharField(max_length=100, verbose_name='full name')),
                ('user_type', models.IntegerField(choices=[(1, 'Administrator'), (2, 'Staff / Teacher'), (3, 'Parent'), (4, 'Student')], default=4)),
                ('gender', models.CharField(choices=[(b'm', 'male'), (b'f', 'female')], default=b'm', max_length=1, verbose_name='gender')),
                ('auth', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driji_user', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.ZK_USER_MODEL)),
                ('terminals', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='zkcluster.Terminal', verbose_name='terminals')),
            ],
            options={
                'db_table': 'driji_user',
            },
        ),
        migrations.AddField(
            model_name='phonebook',
            name='driji_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponebooks', to=settings.ZK_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='driji_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.ZK_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='zk_attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='zkcluster.Attendance'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together=set([('driji_user', 'date')]),
        ),
    ]
