# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zkcluster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.SmallIntegerField(choices=[(0, 'User'), (14, 'Administrator')], default=0, verbose_name='privilege')),
                ('password', models.CharField(blank=True, max_length=8, null=True, verbose_name='password')),
                ('group_id', models.CharField(blank=True, max_length=7, null=True, verbose_name='group id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('fullname', models.CharField(max_length=100, verbose_name='full name')),
                ('user_type', models.IntegerField(choices=[(1, 'Administrator'), (2, 'Staff / Teacher'), (3, 'Parent'), (4, 'Student')], default='Student')),
                ('gender', models.CharField(choices=[(b'm', 'male'), (b'f', 'female')], default=b'm', max_length=1, verbose_name='gender')),
                ('attendances', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='zkcluster.Attendance', verbose_name='attendances')),
                ('terminals', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='zkcluster.Terminal', verbose_name='terminals')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driji_profile',
            },
        ),
    ]
