# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zkcluster', '0001_initial'),
        ('driji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSumary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[(b'p', 'present'), (b'a', 'absense'), (b'l', 'late')], max_length=1, verbose_name='status')),
                ('driji_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.ZK_USER_MODEL)),
                ('zk_attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sumary', to='zkcluster.Attendance')),
            ],
            options={
                'db_table': 'driji_attendance_sumary',
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendancesumary',
            unique_together=set([('driji_user', 'date')]),
        ),
    ]
