# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 04:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.ZK_USER_MODEL),
        ),
    ]
