# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='driji_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ponebook', to=settings.ZK_USER_MODEL),
        ),
    ]
